# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='secret_app.User'),
        ),
    ]
