# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Book',
        ),
    ]
