# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='secret_app.User'),
        ),
    ]
